### ISSUE TITLE
Diffie Hellman support

### ISSUE THREAD

**Issue by h4x3rotab** [novifinancial/ristretto255-js#8]
Looks like not too hard to add, but do you plan to add ECDH key agreement to the library?

**Comment by kevinlewi** [comment]
Hi @h4x3rotab, apologies for the delayed response!

This library is intended to be as minimal as possible, while still supporting the core operations for Ristretto255. It should be easy for a consumer of this library to implement ECDH key agreement on top of the functions that we already expose – therefore there are no plans to bake ECDH key agreement into this API at the moment.

Marking this issue as resolved, but please feel free to re-open if you have more questions!

cc: @valerini
